// <auto-generated />
using ConferenceHalls.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConferenceHalls.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919014002_AddAdditionalServices")]
    partial class AddAdditionalServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConferenceHalls.Api.Models.AdditionalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "Name")
                        .IsUnique();

                    b.ToTable("AdditionalServices");
                });

            modelBuilder.Entity("ConferenceHalls.Api.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseHourlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseHourlyPrice = 2000m,
                            Capacity = 50,
                            Name = "Зал A"
                        },
                        new
                        {
                            Id = 2,
                            BaseHourlyPrice = 3500m,
                            Capacity = 100,
                            Name = "Зал B"
                        },
                        new
                        {
                            Id = 3,
                            BaseHourlyPrice = 1500m,
                            Capacity = 30,
                            Name = "Зал C"
                        });
                });

            modelBuilder.Entity("ConferenceHalls.Api.Models.AdditionalService", b =>
                {
                    b.HasOne("ConferenceHalls.Api.Models.Hall", "Hall")
                        .WithMany("AdditionalServices")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ConferenceHalls.Api.Models.Hall", b =>
                {
                    b.Navigation("AdditionalServices");
                });
#pragma warning restore 612, 618
        }
    }
}
